### PR TITLE
Add single sign out middleware

### PR DESCRIPTION
**Pull request by noidi**

### CODE REVIEW

**Comment by olabini** [comment]
I'm not a 100% sure this belong in the project. The current implementation is a very thin cover over the Jasig CAS implementation, while this adds considerable heft. I suspect it would work better in a separate small project.

**Comment by noidi** [comment]
Although under the hood the proposed single sign out implementation is independent of the login functionality, I think that from the user's perspective they belong in the same library. Given the symmetry between the sign-in and sign-out operations, I would expect `clj-cas-client` to provide a single abstraction that covers both.

Even `org.jasig.cas.client/cas-client-core`, which `clj-cas-client` depends on, contains `org.jasig.cas.client.session.SingleSignOutFilter` in addition to `org.jasig.cas.client.authentication.AuthenticationFilter`. Obviously we can't just wrap a a servlet filter that operates on servlet sessions and have it work with Ring – we need a custom reimplementation – but I think the Clojure wrapper should provide the same functionality as the Java library it wraps.

**Comment by olabini** [comment]
Hi,

I understand what you're saying, but I still don't feel comfortable
putting this code into the project. Since it's very easy to create a new
project on clojars, and there is nothing in the new code that depends on
the existing code, and inversely, the easiest path would be to just
separate it.

Cheers

On 07/02/14 05:12, Timo Mihaljov wrote:

> Although under the hood the proposed single sign out implementation is
> independent of the login functionality, I think that from the user's
> perspective they belong in the same library. Given the symmetry between
> the sign-in and sign-out operations, I would expect |clj-cas-client| to
> provide a single abstraction that covers both.
> 
> Even |org.jasig.cas.client/cas-client-core|, which |clj-cas-client|
> depends on, contains |org.jasig.cas.client.session.SingleSignOutFilter|
> in addition to
> |org.jasig.cas.client.authentication.AuthenticationFilter|. Obviously we
> can't just wrap a a servlet filter that operates on servlet sessions and
> have it work with Ring – we need a custom reimplementation – but I think
> the Clojure wrapper should provide the same functionality as the Java
> library it wraps.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/olabini/clj-cas-client/pull/5#issuecomment-34423538.

## 

 Ola Bini (https://olabini.se)

 "Yields falsehood when quined" yields falsehood when quined.

**Comment by noidi** [comment]
I've created a new project, [`cas-single-sign-out`](https://github.com/solita/cas-single-sign-out), and opened #6 to point the users of `clj-cas-client` to it.

**Pull request closed without merging**
